remove csh suffix of script and improve code

diff --git a/transfer-local-ports-wip-to-overlay b/transfer-local-ports-wip-to-overlay
--- a/transfer-local-ports-wip-to-overlay
+++ b/transfer-local-ports-wip-to-overlay
@@ -1,5 +1,10 @@
 #!/bin/csh
 
+# DESCRIPTION: I use the script to transfer my local ports and/or
+# patches or work in progress ports to my own ports overlay on GitHub.
+# DEPENDENCIES: rsync, ports tree
+# AUTHOR: nxjoseph
+
 set id=`id -u`
 set portsdir="/usr/ports"
 set maintainer="nxjoseph@protonmail.com"
@@ -7,7 +12,7 @@ set pureports="$portsdir/pure-ports"
 set portsf="$portsdir/ports"
 set destdir="/home/yusuf/Documents/yusuf-ports-overlay"
 
-if ( "$id" != "0" ) then
+if ( "$id" != 0 ) then
 	echo "please run this as root"
 	exit 1
 endif
@@ -19,17 +24,20 @@ if ( -d "$portsdir" ) then
 		find . -type f -mindepth 3 -maxdepth 3 -iname makefile -exec grep -i "maintainer.*$maintainer" {} + >& "$portsf"
 		cat "$portsf" | awk -F'/' '{print $2"/"$3}' | awk -F':' '{print $1}' > & "$pureports"
 		foreach dir (`cat $pureports`)
-   		# Extract the first directory name
    		set first_dir = `echo "$dir" | cut -d'/' -f1`
-   		
-   		# Create the full destination path
    		set destination_path = "$destdir/$first_dir"
-   		
-   		# Create the destination directory if it doesn't exist
-   		mkdir -p "$destination_path"
-   		
-   		# Copy the directory
+  		if ( ! -d "$destination_path" ) then 	
+			mkdir -p "$destination_path"
+			if ( "$status" != 0 ) then
+				echo "could not create $destination_path"
+				exit 1
+			endif
+		endif
    		rsync -au "$dir" "$destination_path"
+		if ( "$status" != 0 ) then
+			echo "Couldn't copy $dir to $destination_path"
+			exit 1
+		endif
    		
    		echo "Copied $dir to $destination_path"
 		end		
@@ -39,17 +47,10 @@ else
 	exit 1
 endif
 
-if ( -f "$pureports" ) then
-	rm -f "$pureports"
+if ( -f "$pureports" && -f "$portsf") then
+	rm -f "$pureports" "$portsf"
 else
-	echo "$pureports not found"
-	exit 1
-endif
-
-if ( -f "$portsf" ) then
-	rm -f "$portsf"
-else
-	echo "$portsf not found"
+	echo "$pureports & $portsf not found"
 	exit 1
 endif
 
